# Generated by Django 3.2.9 on 2021-11-19 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('city', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=50)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('bankcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankSystem.bank')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('town', models.CharField(max_length=50)),
                ('house_no', models.CharField(max_length=50)),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('loanId', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
                ('Amount', models.DecimalField(decimal_places=2, default=5.0, max_digits=10)),
                ('branchcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankSystem.branch')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankSystem.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('accountNunber', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
                ('Balance', models.DecimalField(decimal_places=2, default=5, max_digits=10)),
                ('street', models.CharField(max_length=50)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('branchcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankSystem.branch')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankSystem.customer')),
            ],
        ),
    ]
